include:
  - backend/docker-compose.yml
networks:
  frontend:

services:
  frontend:
    image: idomi27/vue
    build: 
      context: frontend
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
  proxy:
    image: nginx:1.25-alpine3.17
    depends_on:
      - web
      - frontend
    networks:
      - frontend
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro